### ISSUE TITLE
Creating image base On Json 

### ISSUE THREAD

**Issue by ky5135** [parrots/SignatureToImageDotNet#5]
var signatureImage = sigToImg.SigJsonToImage(signatureJson);
May I know what is the "signatureJson"  and how to get it? please advise and if possible please provide an example.

Thanks.

**Comment by ky5135** [comment]
I found it.
Thanks.

**Comment by parrots** [comment]
In the future please note: Github Issues are not the proper way to request help with libraries you are using. I'd encourage you to only use issue trackers to file actual bugs.
